#!/usr/bin/env bash
# script to domain and sub domain

get_dns_info() {
    domain="$1"
    subdomain="$2"
    sub_dom="${subdomain}.${domain}"
    ip=$(dig "$sub_dom" +short)

    if [ -z "$ip" ]; then
        echo "The subdomain $subdomain does not have a valid DNS record."
    else
        record=$(dig "$sub_dom" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')
        echo "The subdomain $subdomain is a $record record and points to $ip"
    fi
}

main() {
    if [ $# -gt 1 ]; then
        get_dns_info "$1" "$2"
    elif [ $# -eq 1 ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            get_dns_info "$1" "$sub"
        done
    else
        echo "Usage: $0 <domain> [<subdomain>]"
    fi
}

main "$@"
