#!/usr/bin/env bash
# Check if the correct number of arguments is provided
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
server_ip=$2
username=$3
pkey_path=$4 # private key path

# Transfer file to remote directory
scp -o StrictHostKeyChecking=no -i "$pkey_path" "$file_path" "$username@$server_ip":~/
exit 0
