#!/bin/bash
# Install Nginx
apt-get -y update
apt-get -y install nginx

# Start Nginx
service nginx start

# Create a redirection and a page that returns 'Hello World!'
echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    location / {
        return 200 'Hello World!';
    }
}" | tee /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
