#!/usr/bin/env bash
# Install Nginx
apt-get -y update
apt-get -y install nginx

# Start Nginx
service nginx start

# Create a redirection, a page that returns 'Hello World!', and a custom 404 page
echo "server {
    listen 80;
	listen [::]:80;

    server_name _;

	root /var/www/html;
	index index.html index.htm;

    error_page 404 /custom_404.html;
    location  = /custom_404.html {
        root /var/www/html;
        internal;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

}" | tee /etc/nginx/sites-available/default

# Create the custom 404 page
echo "Ceci n'est pas une page" | tee /var/www/html/custom_404.html

# Restart Nginx to apply the changes
service nginx restart
