#!/usr/bin/env bash
# Install Nginx
apt-get -y update
apt-get -y install nginx

# Start Nginx
service nginx start

# Create the directory '/var/www/html/' if it doesn't exist
mkdir -p /var/www/html/

# Create a file named 'index.html' with the content 'Hello World!'
echo 'Hello World!' > /var/www/html/index.html

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Create a redirection, a page that returns 'Hello World!', and a custom 404 page
echo "server {
    listen 80;
	listen [::]:80;

    add_header X-Served-By \$hostname;
    server_name _;

	root /var/www/html;
	index index.html index.htm;

    error_page 404 /custom_404.html;
    location  = /custom_404.html {
        root /var/www/html;
        internal;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

}" > /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
