#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely with a 2 second pause between each iteration
trap "echo 'I am invincible!!!'" SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
