#!/usr/bin/env bash
# allow traffic via ssh, https and http
sudo ufw default deny incoming
sudo ufw allow 22  # Allow SSH (Port 22)
sudo ufw allow 443 # Allow HTTPS (Port 443)
sudo ufw allow 80  # Allow HTTP (Port 80)
sudo ufw enable
