#!/usr/bin/env bash
# Fix my server by reloading, set the servername to suppress the AH0058 error
echo "ServerName localhost" | sudo tee -a /etc/apache2/apache2.conf # >> /etc/apache2/apache2.conf
service apache2 restart